# -*- coding: utf-8 -*-
"""Yuda Sukmana - Random Network.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a7jeSBt-30vyWNmhMANjIXMH6MTrdhdB
"""

import networkx as nx
import matplotlib.pyplot as plt

# generate random  binomial graph dengan N = 100 dan p = 1/6
g = nx.binomial_graph(100, 1/6)


# draw graph!
plt.figure(figsize=(25, 25))
nx.draw(g, edge_color='#FFDEA2', node_size=600, pos=nx.spring_layout(g))
plt.show()
